### ISSUE TITLE
Unable to import Bootstrap stylesheets

### ISSUE THREAD

**Issue by pvlvstepan** [justgeek/nextjs-global-sass#1]
Hi, great solution to using SCSS with NextJS! I've been looking for something like this for a while.

Everything works fine as expected, except one thing - I can't seem to be able to import Bootstrap in any place of the application, whether it's in `_app` component or global SCSS stylesheet via `@import`

I get the following error every time I try to import bootstrap...

```
./node_modules/bootstrap/dist/css/bootstrap.css:5:0
Module not found: Invalid generator object. Asset Modules Plugin has been initialized using a generator object that does not match the API schema.
 - generator has an unknown property 'filename'. These properties are valid:
   object { dataUrl? }
   -> Generator options for asset/inline modules.

Import trace for requested module:
./node_modules/bootstrap/dist/css/bootstrap.css
./src/pages/_app.page.tsx

https://nextjs.org/docs/messages/module-not-found
```

I am using the exact setup as in this repo + `Bootstrap 5.1.3`

Importing Bootstrap via CDN, on the other hand, works perfectly fine

```
<Head>
            <link
                href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
                rel="stylesheet"
                integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
                crossOrigin="anonymous"
            />
</Head>
```

**Comment by justgeek** [comment]
Thanks for reporting this @pvlvstepan Let me try to install bootstrap and push a fix

**Comment by justgeek** [comment]
@pvlvstepan the issue has been solved with work around. Please confirm it is working for you

**Comment by pvlvstepan** [comment]
@justgeek thanks, I was able to get everything working 😁
